services:
  console-db:
    image: postgres:15
    container_name: sampledb
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d